# Playbook for Buffalo BHR-4GRV
- name: setup OpenWrt
  hosts: openwrt 
  become: True 
  vars:
    default_gw: 192.168.57.1
    dns_server: 8.8.8.8
    mqtt_server: 192.168.57.1
    mqtt_port: 1883
  tasks:
  - name: add route to default gw permanently 
    command: "{{item}}"
    with_items:
     - uci set network.wan.gateway={{default_gw}}
#     - uci add_list dhcp.@dnsmasq[-1].server={{dns_server}}
     - uci commit
     - /etc/init.d/network reload
#     - /etc/init.d/dnsmasq reload
    failed_when: False
  - name: install packages 
    opkg: name={{item}} state=present update_cache=yes
    with_items:
      - python-pip
      - ip
      - tcpdump
      - openvswitch
      - coreutils-stty
      - kmod-usb-serial
      - kmod-usb-serial-ftdi
      - mosquitto
      - mosquitto-client
      - libmosquitto
#     - kmod-usb-ohci
#     - kmod-usbip
#     - kmod-usbip-server
#     - kmod-usbip-client
#     - usbip
#     - usbip-client
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip_1.1.1-2_ar71xx.ipk
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip-client_1.1.1-2_ar71xx.ipk
#     - http://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/usbip-server_1.1.1-2_ar71xx.ipk
      - udev
      - usbutils
  - name: add pip modules 
    command: pip install "{{item}}"
    with_items:
      - paho-mqtt
      - pyyaml
      - pyserial
  - name: copy agent config 
    template: src=agent/agent.j2 dest=/root/agent.yaml
  - name: copy agent
    copy: src=agent/agent.py dest=/root/agent.py owner=root mode=0700 

